# Generated by Django 4.2.7 on 2023-11-01 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField()),
                ('confirmed', models.BooleanField()),
                ('sanctioned', models.BooleanField()),
                ('location', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('abbreviation', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=150)),
                ('sanctioned', models.BooleanField()),
                ('region', models.CharField(default='', max_length=100)),
                ('logo', models.ImageField(upload_to='')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule', to='track_api.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Skater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=100)),
                ('skater_name', models.CharField(default='', max_length=100)),
                ('skater_number', models.CharField(default='', max_length=4)),
                ('birth_year', models.CharField(default='', max_length=10)),
                ('pronouns', models.CharField(default='', max_length=20)),
                ('insurance_number', models.CharField(default='', max_length=10)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team', to='track_api.team')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_team', to='track_api.team'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='visiting_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='visiting_team', to='track_api.team'),
        ),
    ]
